AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    EnvironmentName: 
      Description: An environment name that will be prefixed to resources names
      Type: String 
    myUsername:
      Description:  The username to access specific DB
      Type: String
    myPassword:
      Description: password of the username 
      Type: String
    
Resources: 
  DBsubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "subnet to use for DB"
      DBSubnetGroupName: "Subnet Group"
      SubnetIds : 
        - Fn::ImportValue:
            !Sub ${EnvironmentName}-PRI1-SN
        - Fn::ImportValue:
            !Sub ${EnvironmentName}-PRI2-SN
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBName: mmDB
      MultiAZ: true
      PubliclyAccessible: false
      DBInstanceClass: db.t2.small
      Engine: "mysql"
      MasterUsername: !Sub "${myUsername}"
      MasterUserPassword: !Sub "${myPassword}"
      DBSubnetGroupName: !Ref DBsubnetGroup
      Tags:
        - 
          Key: "name"
          Value: !Sub "${EnvironmentName} MySql DB"
    DeletionPolicy: Retain


